# Dockerfile na pasta ./backend
# Use uma imagem do JDK para compilar e executar a aplicação
FROM openjdk:17-jdk-alpine

# Configure o diretório de trabalho
WORKDIR /app

# Copie o arquivo JAR gerado para o contêiner
COPY target/backend-application.jar app.jar

# Exponha a porta usada pela aplicação
EXPOSE 8080

# Execute a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]
