# Dockerfile na pasta ./frontend
# Use uma imagem Node.js para compilar a aplicação
FROM node:18 as build

# Crie e configure o diretório de trabalho
WORKDIR /app

# Copie os arquivos de configuração e o package.json
COPY package.json package-lock.json ./

# Instale as dependências
RUN npm install

# Copie o restante dos arquivos para o contêiner
COPY . .

# Compile a aplicação para produção
RUN npm run build

# Use uma imagem NGINX para servir os arquivos estáticos
FROM nginx:1.25-alpine

# Copie os arquivos estáticos para o NGINX
COPY --from=build /app/build /usr/share/nginx/html

# Exponha a porta 3000
EXPOSE 3000

# Configure o NGINX para servir os arquivos
CMD ["nginx", "-g", "daemon off;"]
